#Instructions: address and points are specified to mean what you want to store within your local machine
#Note that we don't want a "---" at the end of this file, that would indicate an empty document
# B50-2124B Intern Office
address: 250
points:
    - 0, 50A-2124B Wire1
    - 12, 50A-2124B Wire2
---
# Repeater
address: 25
points:
---
# B72 TRW
address: 28
points:
    - 0, 72 TRW Water Meter
---
# Repeater
address: 29
points:
---
# Repeater
address: 30
points:
---
# B34 CT
address: 31
points:
    - 0, Shasta Water Meter
---
# Repeater
address: 32
points:
---
# 50A-CT Makeup
address: 33
points:
    - 0, 50A CT-5 Makeup
    - 5, 50A CT-6 Makeup
---
# B71 CT
address: 34
points:
    - 0, 71 CT-4 Makeup
    - 5, 71 CT-4 Blowdown
---
# Repeater
address: 36
points:
---
# 50B CT
address: 37
points:
    - 0, 50B CT-4-5 Drain Flow
    - 5, 50B CT-4 Makeup
    - 10, 50B CT-5 Makeup
    - 15, 50B CT-4-5 Makeup From B50
---
# B62 CT
address: 38
points:
    - 0, 62 CT-1-2 Makeup
    - 5, 62 CT-1-2 Blowdown
---
# B62 Gas
address: 39
points:
    - 0, 62 Gas
---
# B34 CT
address: 40
points:
    - 0, 34 CT-1 Makeup
    - 5, 34 CT-2 Makeup
---
# B50A Gas meter, East side
address: 41
points:
    - 0, 50A-East-Gas
---
# B50A Gas meter, West side
address: 42
points:
    - 0, 50A-West-Gas
---
# B70 & 70A Gas
address: 43
points:
    - 0, 70A Gas
    - 5, 70 Gas
---
# B71 Gas
address: 44
points:
    - 0, 71 Gas
---
# B33 Gas Meter
address: 45
points:
    - 0, 33 Gas
---
# B88 Gas
address: 48
points:
    - 0, 88 Gas
---
# B88 CT
address: 49
points:
    - 0, 88 CT-2 Makeup
    - 5, 88 CT-2 Blowdown
---
# B76 Gas
address: 50
points:
    - 0, 76 Gas
---
# B66 Gas
address: 51
points:
    - 0, 66 Gas
