# B50-2124B Intern Office
address: 250
points: 
    - 0, 50A-2124B Wire1
    - 12, 50A-2124B Wire2
---
# B37 CT
address: 22
points:
    - 0, 37-CT Makeup
    - 4, 37-CT Blowdown
---
#B34 CT
address: 28 
points:
    - 0, 34-CT Makeup
    - 4, 34-CT Blowdown