#Instructions: address and points are specified to mean what you want to store within your local machine
#Note that we don't want a "---" at the end of this file, that would indicate an empty document
# B50-2124B Intern Office
address: 250
points:
    - 0, 50A-2124B Wire1
    - 12, 50A-2124B Wire2
---
# B37 CT
address: 22
points:
    - 0, 37-CT Makeup
    - 4, 37-CT Blowdown
---
# B34 CT
address: 28
points:
    - 0, 34-CT Makeup
    - 5, 34-CT Blowdown
---
# 50A-CT-5 & 6 Makeup
address: 33
points:
- 0, 50A CT5 Makeup
- 5, 50A CT6 Makeup

---
# 50B Cooling towers
address: 37
points:
    - 0, 50B-CT-Drain
    - 1, 50B-CT-Drain_rate
    - 5, 50B-CT-4-Makeup
    - 10, 50B-CT-5-Makeup
    - 15, 50B-CT Makeup From B50
    - 20, Input 5
    - 25, Input 6
    - 30, Input 7
    - 35, Input 8
    - 40, Output 01
    - 41, Output 02

---
# B50A Gas meter, East side
address: 41
points:
    - 0, 50A-East-Gas

---
# B33 Gas Meter
address: 45
points:
    - 0, Pulse #1
    - 5, Pulse #5

---
# B88 CT
address: 49
points:
    - 0, Pulse #1
    - 5, Pulse #2